[build-system]
requires = ["pyinstaller>=6.17.0"]

[project]
name = "CLATodoList"
version = "0.3.1"
requires-python = ">=3.13.7"
description = "Simple CLI application for make todo"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Lahanig"}
]
